### PR TITLE
All tidy

### PR DESCRIPTION
**Pull request by hayden-malan**
I've indented the entire html document, even indenting links and abbreviations in paragraphs. I believe my work is up to standard, and will make the document a lot easier to read and navigate.

### CODE REVIEW

**Comment by nick-jac** [comment]
Hi looks good, the only thing is around <abbr> </abbr> I would include all on same line?? That's all.

**Comment by hayden-malan** [comment]
@nick-jac  Thanks for the feedback, which part of the document would need to be changed?

**Comment by nick-jac** [comment]
Hi,

It was just an observation, no changes needed. I’ll go ahead and close the pull request. Do we delete our own tidying branch ourselves? Some of the instructions are a little bit vague.

 

N

**Comment by nick-jac** [comment]
I'll leave you to delete it. Cheers

**Pull request merged**
